#ifndef MLP_H
#define MLP_H

// ============================================================
// FOD MLP accelerator - HLS header
//
// This header declares the 64 -> 32 -> 16 -> 4 integer MLP that
// mirrors the verified Python golden reference:
//
//   Z1 = X_int8 @ W1_int8 + b1_int32 ; A1 = relu(Z1)
//   A1_int8 = round(A1 * S_Z1 / S_A1)
//   Z2 = A1_int8 @ W2_int8 + b2_int32 ; A2 = relu(Z2)
//   A2_int8 = round(A2 * S_Z2 / S_A2)
//   Z3 = A2_int8 @ W3_int8 + b3_int32          (final logits, no ReLU)
//   prediction = argmax(Z3)
//
// Network dimensions, weights, biases and quantization scales all
// come from weights/mlp_weights.h (the golden source of truth).
// This file does NOT redefine or recompute any of those values.
// ============================================================

#include <stdint.h>

// mlp_weights.h defines: INPUT_SIZE, HIDDEN1_SIZE, HIDDEN2_SIZE,
// OUTPUT_SIZE, S_X, S_W1, S_W2, S_W3, S_Z1, S_A1, S_Z2, S_A2, S_Z3,
// W1, b1, W2, b2, W3, b3.
//
// NOTE: adjust this include path to wherever mlp_weights.h lives in
// your project (e.g. "weights/mlp_weights.h"). It is included here
// unmodified, exactly as generated by the Python quantization step.
#include "mlp_weights.h"

// ------------------------------------------------------------
// Per-layer building blocks (Phase 1/2/3 of the debug plan)
// ------------------------------------------------------------

// Phase 1: Dense 64 -> 32, INT32 MAC + bias, ReLU, requantize to INT8
void layer1(const int8_t input[INPUT_SIZE], int8_t output[HIDDEN1_SIZE]);

// Phase 2: Dense 32 -> 16, INT32 MAC + bias, ReLU, requantize to INT8
void layer2(const int8_t input[HIDDEN1_SIZE], int8_t output[HIDDEN2_SIZE]);

// Phase 3: Dense 16 -> 4, INT32 MAC + bias. No ReLU, no requantization.
// Produces the final INT32 logits, exactly like the Python reference.
void layer3(const int8_t input[HIDDEN2_SIZE], int32_t logits[OUTPUT_SIZE]);

// Phase 4: argmax over the 4 INT32 logits.
// Ties resolve to the first (lowest-index) maximum, matching
// numpy.argmax's tie-breaking behavior.
int argmax4(const int32_t logits[OUTPUT_SIZE]);

// ------------------------------------------------------------
// Top-level accelerator function
//
// This is the function you will eventually set as the Vitis HLS
// top-level function ("Set Top") once the algorithm is verified in
// C simulation. For this initial phase it is a plain function call
// with simple array arguments only - no AXI, no streaming, no
// pragmas - so that C simulation is as simple as possible to debug.
// ------------------------------------------------------------
void mlp_top(
    const int8_t input[INPUT_SIZE],
    int32_t logits[OUTPUT_SIZE],
    int &pred_class
);

#endif // MLP_H
